serviceMonitor:
  enabled: true
  namespace: monitoring
  additionalLabels:
    release: kube-prom-stack
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 65534
  runAsGroup: 65534
  seccompProfile:
    type: RuntimeDefault
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
config:
  extraArgs:
    - --tls.insecure-skip-verify
